### ISSUE TITLE
Multibody-STLs of Nightwatch_Cover don't have multiple bodies

### ISSUE THREAD

**Issue by steadyjaw** [VoronDesign/Pocket-Watch#7]
Objects of the logo are missing in both versions of the Nigthwatch cover STL files.
Multibody and non-multibody STLs seem to be the same files:
![image](https://user-images.githubusercontent.com/36079537/218712965-7d34d745-1eeb-4bda-bbbc-7c5f16b4b4a7.png)

**Files affected:**
https://github.com/VoronDesign/Pocket-Watch/blob/1cc59c227c98b0a841a6bc03f25a3c1093c5cc8e/STLs/%5Ba%5D_Nightwatch_Cover_ECAS04_Multibody_Logo_x1.stl
https://github.com/VoronDesign/Pocket-Watch/blob/1cc59c227c98b0a841a6bc03f25a3c1093c5cc8e/STLs/%5Ba%5D_Nightwatch_Cover_M10_Multibody_Logo_x1.stl

Image from the slicer:
![image](https://user-images.githubusercontent.com/36079537/218711988-b4209354-2144-400d-9df4-72771d85d698.png)

**Comment by SinisterRj** [comment]
I found the same error.

**Comment by nemgrea** [comment]
fixed
